version: "3.8"

services:
  meta-ads-api:
    build: .
    container_name: meta-ads-api
    restart: always
    environment:
      TZ: Europe/Moscow
      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
      META_APP_ID: ${META_APP_ID}
      META_APP_SECRET: ${META_APP_SECRET}

    #command: sh script.sh
    volumes:
      - /home/get/logs_all/meta_ads_api/:/app/logs/
    
  nginx:
    container_name: nginx-meta-ads-api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - meta-ads-api
    restart: always
    environment:
      - "TZ=Europe/Moscow"
    ports:
      - 8081:80
      - 4449:443
    volumes:
      - /home/get/cert:/app/cert


    
