swagger: "2.0"
info:
  title: "Meta marketing ECOM API Documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/metamarketing/getads":
    post:
tags:
  - ads
summary: "Get ads"
description: "Get ads info. By ad account, by ad campaign or by ad set"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      account_id:
        type: "integer"
        example: 1234567890
        description: Ads account id
      user_token:
        type: "string"
        example: "asddfg22emn2ej0983e47"
        description: User token
      campaign_id:
        type: "integer"
        example: 1234567890
        description: Campaign id (not required)
      adset_id:
        type: "integer"
        example: 1234567890
        description: Adset id (not required)
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"