swagger: "2.0"
info:
  title: "Meta marketing ECOM API Documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/metamarketing/getcampaigns":
    post:
tags:
  - campaigns
summary: "Get campaigns"
description: "Get campaigns info"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      account_id:
        type: "integer"
        example: 1234567890
        description: Ads account id
      user_token:
        type: "string"
        example: "asddfg22emn2ej0983e47"
        description: User token
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"
